In [1]:
import tensorflow as tf

# Zero Dimensinal Tensor (***Scalar***)

## Tensor Declaration

In [2]:
x = tf.constant(value = 3, dtype = 'uint8')
y = tf.constant(value = [[4]], dtype = 'float16')
z = tf.constant(value = 5, shape = (1, 1), dtype = 'float32')

In [3]:
print(x)
print(y)
print(z)

tf.Tensor(3, shape=(), dtype=uint8)
tf.Tensor([[4.]], shape=(1, 1), dtype=float16)
tf.Tensor([[5.]], shape=(1, 1), dtype=float32)


## Basic Math Operations

In [4]:
x = tf.constant(value = 5.6723, dtype = 'float16')
y = tf.constant(value = 7.454, dtype = 'float16')

In [5]:
sum = tf.add(x, y)
subtract = tf.subtract(x, y)
multiply = tf.multiply(x, y)
divide = tf.divide(x, y)

In [6]:
print(f'Sum : {sum}, Subtract : {subtract}, Multiply : {multiply}, Divide : {divide}')

Sum : 13.125, Subtract : -1.78125, Multiply : 42.28125, Divide : 0.76123046875


# One Dimensional Tensor (***Vector***)

## Tensor Declaration

In [7]:
x = tf.constant(value = [[3.463, 5.47, 24.178, 3.134]], dtype = 'float16')
y = tf.constant(value = [[4.4738, 49.37, 2.343, 7.328]], dtype = 'float16')

In [8]:
print(x)
print(y)

tf.Tensor([[ 3.463  5.47  24.17   3.135]], shape=(1, 4), dtype=float16)
tf.Tensor([[ 4.473 49.38   2.344  7.33 ]], shape=(1, 4), dtype=float16)


### Basic Math Operations

In [9]:
sum = tf.add(x, y)
subtract = tf.subtract(x, y)
multiply = tf.multiply(x, y)
divide = tf.divide(x, y)

dot_product = tf.reduce_sum(tf.multiply(x, y))

In [10]:
print(f'Element wise Sum : {sum}, Element wise Subtract : {subtract}, Element wise Multiply : {multiply}, Element wise Divide : {divide}, \nDot Product : {dot_product}')

Element wise Sum : [[ 7.938 54.84  26.52  10.46 ]], Element wise Subtract : [[ -1.01  -43.9    21.83   -4.195]], Element wise Multiply : [[ 15.49 270.    56.66  22.97]], Element wise Divide : [[ 0.7744  0.1108 10.31    0.4277]], 
Dot Product : 365.0


# Two Dimensional Tensor (***Matrix***)

## Tensor Declaration

In [11]:
x = tf.random.normal(shape = (3, 3), stddev = 1, mean = 0)
y = tf.random.uniform(shape = (3, 3), minval = -1, maxval = 1)

In [12]:
print(x)
print(y)

tf.Tensor(
[[ 0.707285    1.1619828  -0.16983266]
 [ 1.4794102  -0.6452456  -1.5128297 ]
 [-0.12375502  0.8985882  -0.76404774]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.09212756 -0.2275703  -0.18839931]
 [ 0.35876703 -0.57464814  0.9745755 ]
 [ 0.2488699  -0.8006971   0.10936785]], shape=(3, 3), dtype=float32)


## Basic Math Operations

In [13]:
sum = tf.add(x, y)
subtract = tf.subtract(x, y)
multiply = tf.multiply(x, y)
divide = tf.divide(x, y)

dot_product = tf.reduce_sum(tf.multiply(x, y))

In [14]:
print(f'Element wise Sum : {sum}, \nElement wise Subtract : {subtract}, \nElement wise Multiply : {multiply}, \nElement wise Divide : {divide}, \nDot Product : {dot_product}')

Element wise Sum : [[ 0.6151574   0.9344125  -0.35823196]
 [ 1.8381772  -1.2198937  -0.53825414]
 [ 0.12511487  0.09789109 -0.6546799 ]], 
Element wise Subtract : [[ 0.79941255  1.3895531   0.01856665]
 [ 1.1206431  -0.07059747 -2.4874053 ]
 [-0.37262493  1.6992853  -0.8734156 ]], 
Element wise Multiply : [[-0.06516044 -0.26443276  0.03199636]
 [ 0.5307636   0.3707892  -1.4743668 ]
 [-0.0307989  -0.71949697 -0.08356225]], 
Element wise Divide : [[-7.6772356  -5.106039    0.9014505 ]
 [ 4.1235957   1.1228534  -1.5522959 ]
 [-0.49726796 -1.1222574  -6.9860363 ]], 
Dot Product : -1.7042689323425293


## Type Casting

In [15]:
x = tf.cast(x, dtype = 'int8')
y = tf.cast(y, dtype = 'float16')

In [16]:
print(x)
print(y)

tf.Tensor(
[[ 0  1  0]
 [ 1  0 -1]
 [ 0  0  0]], shape=(3, 3), dtype=int8)
tf.Tensor(
[[-0.0921 -0.2275 -0.1884]
 [ 0.359  -0.5747  0.9746]
 [ 0.2489 -0.801   0.1094]], shape=(3, 3), dtype=float16)


# Indexing a Tensor

In [17]:
x = tf.random.normal(shape = (1, 10), mean = 5, stddev = 10)

In [18]:
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor(
[[ 18.11633   -11.194359    9.821027    1.4568758  -5.4163837  -3.8088655
   14.689409    8.3194065   2.5618904  11.080187 ]], shape=(1, 10), dtype=float32)
tf.Tensor([], shape=(0, 10), dtype=float32)
tf.Tensor([], shape=(0, 10), dtype=float32)
tf.Tensor(
[[ 18.11633   -11.194359    9.821027    1.4568758  -5.4163837  -3.8088655
   14.689409    8.3194065   2.5618904  11.080187 ]], shape=(1, 10), dtype=float32)
tf.Tensor(
[[ 18.11633   -11.194359    9.821027    1.4568758  -5.4163837  -3.8088655
   14.689409    8.3194065   2.5618904  11.080187 ]], shape=(1, 10), dtype=float32)


# Reshaping a Tensor

In [19]:
x = tf.range(9)
y = tf.reshape(x, shape = (3, 3))
z = tf.transpose(y)

In [20]:
print(x)
print(y)
print(z)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
